fix(internal-deployment): Fix concurrency name & error exit logic (#2698)
## Describe your changes
Fix concurrency name and exit on error explicitly

## Issue ticket number and link


## Checklist before requesting a review (skip if just adding/editing
APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

diff --git a/.github/workflows/deploy-scripts-internally.yaml b/.github/workflows/deploy-scripts-internally.yaml
--- a/.github/workflows/deploy-scripts-internally.yaml
+++ b/.github/workflows/deploy-scripts-internally.yaml
@@ -6,7 +6,7 @@ on:
             - master
 
 concurrency:
-    group: templates-${{ github.event.pull_request.number || github.ref }}
+    group: deploy-templates-${{ github.event.pull_request.number || github.ref }}
     cancel-in-progress: true
 
 jobs:
@@ -32,6 +32,7 @@ jobs:
 
             - name: Process and deploy integrations
               run: |
+                  set +e
                   dirs=$(find integration-templates -maxdepth 1 -type d | tail -n +2)
                   for dir in $dirs; do
                     integration=$(basename "$dir")
@@ -50,6 +51,9 @@ jobs:
                     if [ $? -eq 0 ]; then
                       echo "Warning: Unknown provider config for $integration"
                       continue
+                    else
+                      echo "Error in deployment for $integration: $response"
+                      exit 1
                     fi
 
                     cd -
