[gh-#1029] indentation

diff --git a/.github/workflows/integration-flows.yaml b/.github/workflows/integration-flows.yaml
--- a/.github/workflows/integration-flows.yaml
+++ b/.github/workflows/integration-flows.yaml
@@ -7,40 +7,40 @@ concurrency:
     cancel-in-progress: true
 
 jobs:
-  flow-compilation:
-    runs-on: ubuntu-latest
+    flow-compilation:
+        runs-on: ubuntu-latest
 
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v3
 
-    - name: Install Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
+            - name: Install Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: '18'
 
-    - name: Install nango CLI
-      run: |
-        npm install -g nango
-        # TODO this shouldn't be needed
-        npm install @tsconfig/node18-strictest-esm --save-dev
+            - name: Install nango CLI
+              run: |
+                npm install -g nango
+                # TODO this shouldn't be needed
+                npm install @tsconfig/node18-strictest-esm --save-dev
 
-    - name: Compile with Nango
-      run: |
-        set -e
-        cd integration-templates
-        for dir in */; do
-          if [[ "$dir" != "." && "$dir" != "integration-templates/" ]]; then
-              cd "$dir"
-              mkdir -p nango-integrations
-              find . -maxdepth 1 ! -name '.' ! -name 'nango-integrations' -exec mv -t nango-integrations {} +
-              cd nango-integrations
-              output=$(nango compile 2>&1)
-              echo "$output"
-              if [[ "$output" == *"Error compiling"* ]]; then
-                echo "Error found in directory $dir"
-                exit 1
-              fi
-              cd ../../
-          fi
-        done
+            - name: Compile with Nango
+              run: |
+                set -e
+                cd integration-templates
+                for dir in */; do
+                  if [[ "$dir" != "." && "$dir" != "integration-templates/" ]]; then
+                      cd "$dir"
+                      mkdir -p nango-integrations
+                      find . -maxdepth 1 ! -name '.' ! -name 'nango-integrations' -exec mv -t nango-integrations {} +
+                      cd nango-integrations
+                      output=$(nango compile 2>&1)
+                      echo "$output"
+                      if [[ "$output" == *"Error compiling"* ]]; then
+                        echo "Error found in directory $dir"
+                        exit 1
+                      fi
+                      cd ../../
+                  fi
+                done
